### ISSUE TITLE
Duplicate Messages/Responses

### ISSUE THREAD

**Issue by ChrisMissal** [HeadspringLabs/hsbot#43]
Some scripts are duplicating responses:

- [x] echo
- [x] help
- [x] image/animate/youtube
- [x] map me
- [x] mustache
- [x] ping
- [x] pug me
- [x] pug bomb
- [x] the rules
- [x] random memory
- [x] tables

**Comment by bardoloi** [comment]
Investigating whether it could be related to these reported issues: https://github.com/github/hubot/issues/919
https://github.com/github/hubot/issues/71

**Comment by ChrisMissal** [comment]
This will be fixed when the `azure` branch is merged in.
