### ISSUE TITLE
Move env variable declarations outside of bash script

### ISSUE THREAD

**Issue by hulahomer** [HeadspringLabs/hsbot#44]
In the move from Heroku to Azure, there is no way to specify environment variables on the Linux VM hsbot is hosted on via the Web UI (unlike Heroku), so for now we have declared those variables in the bash script that gets run on the VM to run/restart hsbot.

We should move these out of that bash script and into something like Vault, Azure KeyVault, or something similar.

**Comment by DanMalagari** [comment]
I like the idea of Azure KeyVault, but they cannot be modified through our Azure portal.  They would still have to be modified using Powershell, which doesn't really simplify the process.

**Comment by hulahomer** [comment]
Maybe if hsbot was a web app or job then we could use the env variables you can set there? I know web apps have them now, but not sure about web jobs.

**Comment by ChrisMissal** [comment]
Web Jobs still don't have the application settings that apps do, **BUT** if the web job can "reach out" to something before it runs for any secret keys/variables, that could work.

**Comment by hulahomer** [comment]
Closing this since we aren't using the bash script anymore to keep hsbot alive on a Linux VM
