### ISSUE TITLE
Research Dokku

### ISSUE THREAD

**Issue by ChrisMissal** [HeadspringLabs/hsbot#56]
Currently, out hsbot VM is quite crude. Perhaps [Dokku](https://github.com/progrium/dokku) would provide a better/nicer/cleaner environment.
- [Migrating Hubot from Heroku to Dokku](http://theflyingdeveloper.com/hubot-on-dokku/)

**Comment by hulahomer** [comment]
Closing this one since we have since moved to Azure Websites where it functions without the need for a Linux VM.
