### ISSUE TITLE
hsbot brag does not work in 1st Floor Austin room

### ISSUE THREAD

**Issue by DanMalagari** [HeadspringLabs/hsbot#57]
Trying to brag and getting no response in the 1st Floor Austin room.  hsbot still responds to other commands.  When connected to the hsbot VM, an error is thrown on line 139.

**Comment by hulahomer** [comment]
@DanMalagari what's the error? can you screenshot the it in the log and paste it here?

**Comment by DanMalagari** [comment]
Just tried to replicate and it seems to have fixed itself after rebooting hsbot.

**Comment by allenpiscitello** [comment]
Have you tried turning it off and on again?
