### ISSUE TITLE
Confme.coffee does not work

### ISSUE THREAD

**Issue by DanMalagari** [HeadspringLabs/hsbot#72]
The command 'hsbot conf rooms Austin' previously pulled up all information around the Austin conference rooms.  It used an XML file on Azure to store the information.

The script needs to be updated to make use of Azure's blob storage, or needs to be removed.

**Comment by gbHeadspring** [comment]
Recommend killing this off - the "hsbot where is" command is sufficient,
and I doubt we're going to keep a separate XML file up to date with room
configuration changes etc.

Best Regards,
Glenn G. Burnside III
​ | E​
VP, Operations
​
 | ​
512.827.8167 <512.413.4794>

**Comment by hulahomer** [comment]
Agreed :+1: if no one uses it, then this one can go away

**Comment by DanMalagari** [comment]
Removed confme.coffee with my latest push.
